version: "3.8"
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  web:
    build: .
    environment:
      FLASK_ENV: development
      FLASK_APP: app.py
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - redis

  celery_worker:
    build: .
    command: celery -A celery_worker worker --loglevel=info
    depends_on:
      - redis
      - web
